name: NovaTNTTag
main: net.novauniverse.games.tnttag.NovaTNTTag
description: Novauniverse TNTTag
version: 1.0
depend: [NovaCore, NovaCoreGameEngine]
softdepend: [NovaGamesTarget]

authors: [Zeeraa, NovaUniverse]